### PR TITLE
Fix: the button didn't respond correctly when hovered

### LINKED ISSUE #6: Buttons don't indicate they are pressable
Multiple buttons/places you can click don't change the cursor to show that they are clickable, including: right navbar buttons, main page "get started" and "explore all characters" buttons & possibly more.

### PR DESCRIPTION
**Pull request by Matei5**
Fixed #6 
The buttons didn't respond correctly when hovered so I modified the button component and used it everywhere in the code

### CODE REVIEW

File: JunoChat-frontend/src/pages/ChatsHistoryPage.tsx [hunk 1]
```diff
@@ -1,7 +1,7 @@
 import React, { useEffect, useState } from 'react';
 import { useNavigate } from 'react-router-dom';
 import {getChatHistory} from '@/api'; 
-import { Button } from '@/components/ui/uiButton';
+import { Button } from '@/components/Button';
```
Comment (Matei5) [inline JunoChat-frontend/src/pages/ChatsHistoryPage.tsx:4]: Why are you moving from /ui/uiButton to a /Button
